### ISSUE TITLE
Peer Review by Claire Chang

### ISSUE THREAD

**Issue by ClaireUoft** [danield424/TTC-Streetcar-Delays#1]
Opening statement summary

I am peer-reviewing Daniel's paper on TTC Streetcar Delays project delays in Toronto's streetcar system.

Strong positive points

The repository is well-organized, making it easy for users to follow the data processing steps. There are well-formatted graphs and tables in the paper.

Critical improvements needed

The project would benefit from a more detailed description in the Abstract, and details such as why specific data cleaning steps were taken or why certain variables were included or excluded. Additionally, the repository lacks a comprehensive explanation of the project’s purpose and outcomes in the README file. 

Suggestions for improvement

Enhance the README file with a detailed explanation of the project objectives, and key findings.
Make sure you review Chapter 2 on how to properly cite in R 
Remember to not show any R code in the final paper
Adding a subtitle can show more about what are you researching 

Please consider adding/changing/removing:

Add a project summary with the main findings and recommendations.
Change the name of your Rproj.
Add more in-depth descriptions of each script’s purpose in the README.
Add proper references to sources or documentation 

Evaluation:

Based on the evaluation criteria, the repository is solid but would benefit from additional context and clarity in documentation.

Estimated mark:

66 out of 100.

Reason:

The project is technically sound and well-organized, but the lack of a comprehensive project overview and detailed explanations.

**Comment by danield424** [comment]
Thank you for the feedback! I have taken it into account.
