### ISSUE TITLE
Peer Review by Kevin Roe

### ISSUE THREAD

**Issue by Kanghyunroe** [danield424/TTC-Streetcar-Delays#2]
Opening statement summary

The paper investigates TTC Street Car Delay times based on data from Open Data Toronto. 

Strong positive points

- The paper is well organized with properly organized sections
- Graphs are well made and easy to understand. The colours are well chosen and it shows a good summary of what you were trying to find.

Critical improvements needed

- Do not make code visible in the rendered pdf of your paper. This is a critical error that should be fixed
- Make sure to have an abstract in your paper, it is currently incomplete
- Add in-text citations and build out the citation portion

Suggestions for improvement:

- It would be better to further analyze any limitations and next steps with the paper. I feel the discussion session could be further fleshed out to include further insights about the paper and tie your findings to a general statement. 
- Figure 1 is a bit aesthetically unpleasing, you should spend sometime formatting the tables so it fits our style guidelines. 
- Commentary on the measurement of the data is missing - it would be important to add this in future versions of the paper

Please consider adding/changing/removing:

- Consider adding more informative captions for figures
- Change the name of your Rproj.
- More indepth description in your README
- Add proper citations
- add a table of contents for ease of use purposes

Evaluation: 
- Title 1/2
- Author, date and repo: 2/2
- abstract: 0/4
- introduction 2/4
- data 3/10
- measurement 0/4
- prose 4/6
- cross references 0/1
- captions: 1/2
- graphs/tables/etc 2/4
- referencing 0/4
- commits 2/2
- sketches 2/2
- simulation 4/4
- tests 3/4
- reproducibility 2/4
- code style 1/1
- general excellence 1/3
Estimated mark: 29/65

45 out of 100.

Reason:

Based on the fact there are several code blocks in the rendered pdf, no citations, and uninformative captions. The paper is overall not complete and certain sections are missing

**Comment by danield424** [comment]
Thank you for the feedback! I have taken it into account.
