### ISSUE TITLE
Peer Review #3

### ISSUE THREAD

**Issue by GauravT-crypto** [danield424/TTC-Streetcar-Delays#3]
**Opening statement summary:**

This project focuses on analyzing the delay times for the TTC streetcars in Toronto in 2023. The data provided by Open Toronto shows a detailed overview of delay times that were experienced for TTC streetcars and the trends and observations in delays.

**Strong positive points:**

The paper provides a great overview of delays that occurred throughout the months in 2023 and the graphs are visually appealing and displayed well with the information collected.

**Critical improvements needed:**

Code is visible in the paper, so please remember to fix the errors in your document so the code is displayed in it's graph format. The abstract is currently incomplete so remember to add that in soon as well. Some of the graphs are condensed together like in figure 3, so I would recommend to spread them out more, so the reader can visually understand them better apart.

**Suggestions for improvement:**

Some of the graphs are too condensed together, so it be better to spread them out more. Also, some of the tables are cut off like in figure 1 so I would take a look at your code again to make sure that they are displayed more properly on your PDF. Finally your code needs to be removed from being visual on the paper and working properly, so please make sure to fix the errors. 

**Evaluation:** 

If I had to grade this section, I would assign it a grade of 60. The paper provides a good overview of data for the TTC streetcar delays in 2023 and there are okay graphs available and some are visually appealing. However, the paper is still incomplete and the issues above needs to be addressed. 

**Estimated mark:**

60

**Reason:**

The paper provides a good overview of the topic, while also providing some good graphs and relevant data to back up the topic. However, there are some issues with the graphs and other problems with the paper like visible code and uncompleted sections, so once the changes have been made and all sections are completed the quality of the paper and grade will improve.

**Comment by danield424** [comment]
Thank you for the feedback! I have taken it into account.
