### ISSUE TITLE
Peer Review - Vandan

### ISSUE THREAD

**Issue by vandanppatel** [danield424/TTC-Streetcar-Delays#4]
**Opening Statement Summary:**

The paper titled An Analysis of TTC Streetcar Delay Times by Daniel offers a data-driven analysis of streetcar delays in Toronto, focusing on the extent, frequency, and duration of delays. The paper effectively presents the data cleaning and analytical processes, using R and various packages, to explore key trends and patterns in the delay data for 2023. However, while the analysis provides significant insights, the paper could benefit from further discussion and contextualization of its findings and implications.

**Strong Positive Points:**
- The data visualization and statistical analysis are clearly presented, particularly the comparison of delay times across different streetcar lines and services.
- The paper uses robust data cleaning techniques and visualization tools (e.g., ggplot2) to ensure clarity in the findings.

**Critical Improvements Needed:**

1. While the paper presents data well, it lacks a thorough discussion of the impact of streetcar delays on commuter behavior or city infrastructure planning. It would benefit from including research or case studies that show how similar data has been used in transportation planning.
   
2. The paper mentions the use of the `opendatatoronto` package, but it does not provide enough detail on how the data is collected and how reliable it is. An additional section elaborating on the data's source, limitations, and potential biases would be helpful.

3. The explanation for removing "extreme outlier delays" is not sufficiently detailed. It is essential to clarify the thresholds used and justify why certain delays were excluded. This would add more transparency to the analysis process.

4. The paper mentions in the discussion that it would be valuable to compare the 2023 data with 2024, but it stops short of including this comparison. Including even a partial dataset for 2024 could provide a more dynamic look at trends over time.

**Suggestions for Improvement:**

1. The conclusion of the paper could further synthesize the findings and suggest actionable steps for addressing the delay issues identified. Are there operational changes that could be made to reduce these delays? What policy recommendations could be drawn from this data?

2. While the introduction sets the stage for the paper, adding more information about the broader implications of public transport inefficiency (e.g., environmental impacts, economic costs, social inequality) would provide a more compelling reason for the analysis.

3. While the graphs provide essential data, they could benefit from additional labels, captions, and perhaps different colour schemes to ensure accessibility for all audiences, especially those with colour vision deficiencies.

4. Based on the data, the paper should offer clear recommendations for the Toronto Transit Commission. For instance, addressing specific service times or lines that experience the most delays.

5. A deeper engagement with external literature on public transit delays, particularly studies that have employed similar methods, would strengthen the theoretical grounding of the analysis.

**Evaluation:**

Based on the rubric provided in the assignment criteria, this paper meets many of the technical requirements but lacks depth in its discussion and real-world applicability. The visualizations and statistical work are strong, but the paper would greatly benefit from further contextualization and more specific recommendations based on the data.

Here is a detailed mark breakdown based on the rubric provided in the assignment criteria (shown in screenshots):
R is Cited 1/1 
2. LLM Usage Documented 1/1
Title 2/2
Author, Date, Repo 2/2
Abstract 3/4
Introduction 3/4
Data 8/10
Measurement 4/4
Cross-References 2/2
Prose 4/6
Graphs/Tables 3/4
Referencing 4/4
Commits 2/2
Sketches 2/2
Simulation 4/4
Tests 4/4
Reproducibility  4/4
Code Style 1/1
General Excellence  2/3

**Estimated Mark:**
88.5 out of 100.

---

**Reason:**
The paper demonstrates solid technical execution and data analysis but needs stronger discussion, contextualization, and actionable recommendations to score higher. The lack of comparison with 2024 data, as mentioned in the discussion, also detracts from the completeness of the paper.

**Comment by danield424** [comment]
Thank you for the feedback! I have taken it into account.
